# kompilator c
CCOMP = gcc

# konsolidator
LOADER = gcc

# opcje optymalizacji:
# wersja do debugowania
#OPT = -g -DDEBUG -O0
# wersja zoptymalizowana do mierzenia czasu
OPT = -g

# pliki naglowkowe
INC = -I../pomiar_czasu

# biblioteki
LIB = -L../pomiar_czasu -lpomiar_czasu -lm

all: fork clone clonedClone

# zaleznosci i komendy
fork: fork.o 
	$(LOADER) $(OPT) fork.o -o fork $(LIB)

# jak uzyskac plik fork.o ?
fork.o: fork.c ../pomiar_czasu/pomiar_czasu.h
	$(CCOMP) -c $(OPT) fork.c $(INC) 

# zaleznosci i komendy
clone: clone.o 
	$(LOADER) $(OPT) clone.o -o clone $(LIB)

# jak uzyskac plik clone.o ?
clone.o: clone.c ../pomiar_czasu/pomiar_czasu.h
	$(CCOMP) -c $(OPT) clone.c $(INC) 

clonedClone: clonedClone.o 
	$(LOADER) $(OPT) clonedClone.o -o clonedClone $(LIB)

clonedClone.o: clonedClone.c ../pomiar_czasu/pomiar_czasu.h
	$(CCOMP) -c $(OPT) clonedClone.c $(INC) 

clean:
	rm -f *.o fork clone
